# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Choco_First_Task' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SwiftyJSON'
  target 'Choco_First_TaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Choco_First_TaskUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
